version: '2'

services:
  rootme_node:
    build: .
    restart: always
    env_file:
      - .env
  mongodb:
    image: docker.io/bitnami/mongodb:4.4
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'

volumes:
  mongodb_data:
    driver: local

networks:
  default:
    external:
      name: rootme
