services:
  rootme_node:
    build: .
    restart: always
    env_file:
      - .env
    networks:
      - rootme
  mongodb:
    image: docker.io/bitnami/mongodb:4.4
    restart: always
    networks:
      - rootme
    ports:
      - "27017:27017"
    volumes:
      - '/opt/jeanracine:/bitnami/mongodb'

networks:
  rootme:
    driver: bridge
