version: "3"

services:
  rootme_node:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    stdin_open: true
    tty: true
    env_file:
      - .env
    networks:
      - rootme
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
  mongodb:
    image: docker.io/bitnami/mongodb:4.4
    restart: always
    networks:
      - rootme
    ports:
      - "27017"
    volumes:
      - '/opt/jeanracine:/bitnami/mongodb'
  tor-node-1:
    image: osminogin/tor-simple
    networks:
      - rootme
    restart: always
  tor-node-2:
    image: osminogin/tor-simple
    networks:
      - rootme
    restart: always
  tor-node-3:
    image: osminogin/tor-simple
    networks:
      - rootme
    restart: always
  tor-node-4:
    image: osminogin/tor-simple
    networks:
      - rootme
    restart: always
  tor-node-chall:
    image: osminogin/tor-simple
    networks:
      - rootme
    restart: always

networks:
  rootme:
    driver: bridge
