version: '2'

services:
  mongodb:
    image: ghcr.io/zcube/bitnami-compat/mongodb:4.4
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /tmp/mongo:/bitnami/mongodb'

networks:
  rootme:
    driver: bridge
